export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const  SET_USER_FOLLOWERS_BEGIN = 'SET_USER_FOLLOWERS_BEGIN' 
export const  SET_USER_FOLLOWERS_SUCCESS = 'SET_USER_FOLLOWERS_SUCCESS' 
export const  SET_USER_FOLLOWERS_ERROR = 'SET_USER_FOLLOWERS_ERROR' 

export const  SET_USER_FOLLOWINGS_BEGIN = 'SET_USER_FOLLOWINGS_BEGIN' 
export const  SET_USER_FOLLOWINGS_SUCCESS = 'SET_USER_FOLLOWINGS_SUCCESS' 
export const  SET_USER_FOLLOWINGS_ERROR = 'SET_USER_FOLLOWINGS_ERROR' 

export const  SET_USER_NOT_FOLLOWINGS_BEGIN = 'SET_USER_NOT_FOLLOWINGS_BEGIN' 
export const  SET_USER_NOT_FOLLOWINGS_SUCCESS = 'SET_USER_NOT_FOLLOWINGS_SUCCESS' 
export const  SET_USER_NOT_FOLLOWINGS_ERROR = 'SET_USER_NOT_FOLLOWINGS_ERROR' 

export const UPDATE_USER_INFO_BEGIN = 'UPDATE_USER_INFO_BEGIN'
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS'
export const UPDATE_USER_INFO_ERROR = 'UPDATE_USER_INFO_ERROR'

export const GET_MY_SUBGREDDIIIT_BEGIN = 'GET_MY_SUBGREDDIIIT_BEGIN'
export const GET_MY_SUBGREDDIIIT_SUCCESS = 'GET_MY_SUBGREDDIIIT_SUCCESS'
export const GET_MY_SUBGREDDIIIT_ERROR = 'GET_MY_SUBGREDDIIIT_ERROR'

export const CREATE_SUBGREDDIIIT_BEGIN = 'CREATE_SUBGREDDIIIT_BEGIN'
export const CREATE_SUBGREDDIIIT_SUCCESS = 'CREATE_SUBGREDDIIIT_SUCCESS'
export const CREATE_SUBGREDDIIIT_ERROR = 'CREATE_SUBGREDDIIIT_ERROR'

export const DELETE_SUBGREDDIIIT_BEGIN = 'DELETE_SUBGREDDIIIT_BEGIN'
export const DELETE_SUBGREDDIIIT_SUCCESS = 'DELETE_SUBGREDDIIIT_SUCCESS'
export const DELETE_SUBGREDDIIIT_ERROR = 'DELETE_SUBGREDDIIIT_ERROR'

export const OPEN_SUBGREDDIIIT_BEGIN = 'OPEN_SUBGREDDIIIT_BEGIN'
export const OPEN_SUBGREDDIIIT_SUCCESS = 'OPEN_SUBGREDDIIIT_SUCCESS'
export const OPEN_SUBGREDDIIIT_ERROR = 'OPEN_SUBGREDDIIIT_ERROR'

export const GET_SUBGREDDIIIT_POSTS_BEGIN = 'GET_SUBGREDDIIIT_POSTS_BEGIN'
export const GET_SUBGREDDIIIT_POSTS_SUCCESS = 'GET_SUBGREDDIIIT_POSTS_SUCCESS'
export const GET_SUBGREDDIIIT_POSTS_ERROR = 'GET_SUBGREDDIIIT_POSTS_ERROR'

export const GET_SUBGREDDIIIT_FOLLOWERS_BEGIN = 'GET_SUBGREDDIIIT_FOLLOWERS_BEGIN'
export const GET_SUBGREDDIIIT_FOLLOWERS_SUCCESS = 'GET_SUBGREDDIIIT_FOLLOWERS_SUCCESS'
export const GET_SUBGREDDIIIT_FOLLOWERS_ERROR = 'GET_SUBGREDDIIIT_FOLLOWERS_ERROR'

export const GET_SUBGREDDIIIT_MODERATORS_BEGIN = 'GET_SUBGREDDIIIT_MODERATORS_BEGIN'
export const GET_SUBGREDDIIIT_MODERATORS_SUCCESS = 'GET_SUBGREDDIIIT_MODERATORS_SUCCESS'
export const GET_SUBGREDDIIIT_MODERATORS_ERROR = 'GET_SUBGREDDIIIT_MODERATORS_ERROR'

export const GET_SUBGREDDIIIT_JOIN_REQUESTS_BEGIN = 'GET_SUBGREDDIIIT_JOIN_REQUESTS_BEGIN'
export const GET_SUBGREDDIIIT_JOIN_REQUESTS_SUCCESS = 'GET_SUBGREDDIIIT_JOIN_REQUESTS_SUCCESS'
export const GET_SUBGREDDIIIT_JOIN_REQUESTS_ERROR = 'GET_SUBGREDDIIIT_JOIN_REQUESTS_ERROR'

export const CREATE_POST_BEGIN = 'CREATE_POST_BEGIN';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const GET_USER_BEGIN = 'GET_USER_BEGIN';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const UPVOTE_POST_SUCCESS = 'UPVOTE_POST_SUCCESS';
export const UPVOTE_POST_ERROR = 'UPVOTE_POST_ERROR';

export const DOWNVOTE_POST_SUCCESS  = 'DOWNVOTE_POST_SUCCESS'
export const DOWNVOTE_POST_ERROR = 'DOWNVOTE_POST_ERROR';

export const DELETE_POST_BEGIN = 'DELETE_POST_BEGIN'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'

export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS'

export const GET_SAVED_POSTS_BEGIN = 'GET_SAVED_POSTS_BEGIN'
export const GET_SAVED_POSTS_SUCCESS = 'GET_SAVED_POSTS_SUCCESS'
export const GET_SAVED_POSTS_ERROR = 'GET_SAVED_POSTS_ERROR'

export const GET_FOLLOWING_SUBGREDDIIITS_BEGIN = 'GET_FOLLOWING_SUBGREDDIIITS_BEGIN'
export const GET_FOLLOWING_SUBGREDDIIITS_SUCCESS = 'GET_FOLLOWING_SUBGREDDIIITS_SUCCESS'
export const GET_FOLLOWING_SUBGREDDIIITS_ERROR = 'GET_FOLLOWING_SUBGREDDIIITS_ERROR'

export const GET_NON_FOLLOWING_SUBGREDDIIITS_BEGIN = 'GET_NON_FOLLOWING_SUBGREDDIIITS_BEGIN'
export const GET_NON_FOLLOWING_SUBGREDDIIITS_SUCCESS = 'GET_NON_FOLLOWING_SUBGREDDIIITS_SUCCESS'
export const GET_NON_FOLLOWING_SUBGREDDIIITS_ERROR = 'GET_NON_FOLLOWING_SUBGREDDIIITS_ERROR'

export const SEND_JOIN_REQUEST_SUCCESS = 'SEND_JOIN_REQUEST_SUCCESS'
export const SEND_JOIN_REQUEST_ERROR = 'SEND_JOIN_REQUEST_ERROR'

export const ACCEPT_JOIN_REQUEST_SUCCESS = 'ACCEPT_JOIN_REQUEST_SUCCESS'
export const ACCEPT_JOIN_REQUEST_ERROR = 'ACCEPT_JOIN_REQUEST_ERROR'

export const REJECT_JOIN_REQUEST_SUCCESS = 'REJECT_JOIN_REQUEST_SUCCESS'
export const REJECT_JOIN_REQUEST_ERROR = 'REJECT_JOIN_REQUEST_ERROR'

export const LEAVE_SUBGREDDIIIT_BEGIN = 'LEAVE_SUBGREDDIIIT_BEGIN'
export const LEAVE_SUBGREDDIIIT_SUCCESS = 'LEAVE_SUBGREDDIIIT_SUCCESS'
export const LEAVE_SUBGREDDIIIT_ERROR = 'LEAVE_SUBGREDDIIIT_ERROR'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const REPORT_POST_SUCCESS = 'REPORT_POST_SUCCESS'
export const REPORT_POST_ERROR = 'REPORT_POST_ERROR'

export const GET_REPORTED_POST_SUCCESS = 'GET_REPORTED_POST_SUCCESS'
export const GET_REPORTED_POST_ERROR = 'GET_REPORTED_POST_ERROR'

export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS'
export const GET_REPORTS_ERROR = 'GET_REPORTS_ERROR';

export const IGNORE_REPORTED_POST_SUCCESS = 'IGNORE_REPORTED_POST_SUCCESS'
export const IGNORE_REPORTED_POST_ERROR = 'IGNORE_REPORTED_POST_ERROR'

export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
export const BLOCK_USER_ERROR = 'BLOCK_USER_ERROR'

export const GET_BLOCKED_FOLLOWERS_BEGIN = 'BLOCKED_FOLLOWERS_BEGIN';
export const GET_BLOCKED_FOLLOWERS_SUCCESS = 'BLOCKED_FOLLOWERS_SUCCESS';
export const GET_BLOCKED_FOLLOWERS_ERROR = 'BLOCKED_FOLLOWERS_ERROR';